name: Snowdev Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/_release.yml
    with:
      working-directory: snowdev
    secrets: inherit
