name: Snowdev Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "snowdev/pyproject.toml"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "snowdev/pyproject.toml"

jobs:
  release:
    uses: ./.github/workflows/_release.yml
    with:
      working-directory: snowdev
    secrets: inherit
